name: Vacha Data Scraper

on:
  schedule:
    - cron: '0 1 * * 2,6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install pandas requests beautifulsoup4
      - run: python scraper.py
      - run: |
          git config --global user.name "Vacha-Bot"
          git config --global user.email "bot@vacha.safety"
          git add data/*.csv
          git commit -m "Auto-update" || echo "No changes"
          git push
