name: Vacha Data Scraper

on:
  schedule:
    # 01:00 UTC е точно 03:00 българско време
    - cron: '0 1 * * 2,6'
  workflow_dispatch: # Това добавя бутон за ръчно пускане

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas requests beautifulsoup4

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name "Vacha-Bot"
          git config --global user.email "actions@github.com"
          git add data/*.csv
          git commit -m "Auto-update data: $(date)" || echo "No changes"
          git push
